lampod: make the API asyncronus
This is fixing the problem that we have when we use lampod
inside an async application and the program will panic
with the following stacktrace.

So we opt out the sync interface, also because rust edition 2024
is started to make a lot of progess on the async rust, and we
make our internal a little bit more clean.

---- lampo_cln_tests::init_connection_test stdout ----
thread 'lampo_cln_tests::init_connection_test' panicked at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: tokio::runtime::context::runtime::enter_runtime
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:68:5
   3: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
   4: tokio::runtime::runtime::Runtime::block_on
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
   5: lampod::jsonrpc::peer_control::json_connect
             at /home/vincent/gittea/work/lampo.rs/lampod/src/jsonrpc/peer_control.rs:34:13
   6: core::ops::function::Fn::call
             at /build/rustc-1.75.0-src/library/core/src/ops/function.rs:79:5
   7: lampo_async_jsonrpc::Handler<T>::run_callback
             at /home/vincent/gittea/work/lampo.rs/lampo-async-jsonrpc/src/lib.rs:69:20
   8: <lampod::jsonrpc::CommandHandler as lampod::handler::external_handler::ExternalHandler>::handle
             at /home/vincent/gittea/work/lampo.rs/lampod/src/jsonrpc.rs:64:26
   9: <lampod::actions::handler::LampoHandler as lampod::actions::Handler>::react
             at /home/vincent/gittea/work/lampo.rs/lampod/src/actions/handler.rs:118:41
  10: lampod::actions::handler::LampoHandler::call
             at /home/vincent/gittea/work/lampo.rs/lampod/src/actions/handler.rs:81:9
  11: tests::lampo_cln_tests::init_connection_test::{{closure}}
             at ./src/lampo_cln_tests.rs:32:33
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rustc-1.75.0-src/library/core/src/future/future.rs:125:9
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rustc-1.75.0-src/library/core/src/future/future.rs:125:9
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:659:57
  15: tokio::runtime::coop::with_budget
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  16: tokio::runtime::coop::budget
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  17: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:659:25
  18: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:404:19
  19: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:658:36
  20: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:737:68
  21: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/scoped.rs:40:9
  22: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context.rs:180:26
  23: std::thread::local::LocalKey<T>::try_with
             at /build/rustc-1.75.0-src/library/std/src/thread/local.rs:270:16
  24: std::thread::local::LocalKey<T>::with
             at /build/rustc-1.75.0-src/library/std/src/thread/local.rs:246:9
  25: tokio::runtime::context::set_scheduler
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context.rs:180:9
  26: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:737:27
  27: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:646:19
  28: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  29: tokio::runtime::context::runtime::enter_runtime
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  30: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  31: tokio::runtime::runtime::Runtime::block_on
             at /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:347:47
  32: tests::lampo_cln_tests::init_connection_test
             at ./src/lampo_cln_tests.rs:42:5
  33: tests::lampo_cln_tests::init_connection_test::{{closure}}
             at ./src/lampo_cln_tests.rs:26:40
  34: core::ops::function::FnOnce::call_once
             at /build/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    lampo_cln_tests::init_connection_test

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 16 filtered out; finished in 7.82s

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>