ci: update to the last cln version on master
------
 > [ 9/12] RUN git clone https://github.com/ElementsProject/lightning.git --branch=master &&     cd lightning &&     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&     ./configure --enable-developer --disable-rust && git submodule update --init --recursive &&     pip3 install --upgrade pip &&     pip3 install mako mistune==0.8.4 mrkd &&     make -j$(nproc) && make install:
9.819   --enable/disable-coverage (default disable)
9.819     Compile with Clang coverage instrumentation
9.819   --enable/disable-address-sanitizer (default disable)
9.819     Compile with address-sanitizer
9.823   --enable/disable-ub-sanitizer (default disable)
9.823     Compile with undefined behaviour sanitizer
9.823   --enable/disable-fuzzing (default disable)
9.823     Compile with fuzzing
9.823   --enable/disable-rust (default enable)
9.823     Compile with Rust support
------
Dockerfile:30
--------------------
  29 |
  30 | >>> RUN git clone https://github.com/ElementsProject/lightning.git --branch=$CLIGHTNING_VERSION && \
  31 | >>>     cd lightning && \
  32 | >>>     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
  33 | >>>     ./configure --enable-developer --disable-rust && git submodule update --init --recursive && \
  34 | >>>     pip3 install --upgrade pip && \
  35 | >>>     pip3 install mako mistune==0.8.4 mrkd && \
  36 | >>>     make -j$(nproc) && make install
  37 |
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/ElementsProject/lightning.git --branch=$CLIGHTNING_VERSION &&     cd lightning &&     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&     ./configure --enable-developer --disable-rust && git submodule update --init --recursive &&     pip3 install --upgrade pip &&     pip3 install mako mistune==0.8.4 mrkd &&     make -j$(nproc) && make install" did not complete successfully: exit code: 1
Service 'lampo' failed to build : Build failed

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>