lnprototest: inject private keys
Currently this is not working because we need to support
the private keys inside lampo itself.

Currently the app crash with `➜  pylampo git:(macros/update-lampo-config) ✗ cat /var/folders/9p/ztdwh6sj3fl4tzvkcldzqsqh0000gn/T/lnpt-lampo-h4s5fefl/lampo/regtest/daemon.log
Error: Option to force a private key not available at the moment`

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>