meta: upgrade cln4rust package
This commit is fixing the crash reported below
caused by cln4rust, so this commit is upgrading
the package by including the commit
50a51ab2280bea22716392717a0e9bcaad4fa218 for cln4rust

stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::result::unwrap_failed
3: core::result::Result<T,E>::unwrap
at /build/rustc-1.75.0-src/library/core/src/result.rs:1077:23
4: tests::lampo_cln_tests::test_lampo_to_cln_close_channel_with_channel_id_success
at ./src/lampo_cln_tests.rs:985:5
5: tests::lampo_cln_tests::test_lampo_to_cln_close_channel_with_channel_id_success::{{closure}}
at ./src/lampo_cln_tests.rs:887:61
6: core::ops::function::FnOnce::call_once
at /build/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.

---- lampo_cln_tests::test_lampo_to_cln_close_channel_without_channel_id_success stdout ----
thread 'lampo_cln_tests::test_lampo_to_cln_close_channel_without_channel_id_success' panicked at tests/tests/src/lampo_cln_tests.rs:1087:28:
called Result::unwrap() on an Err value: JSON decode error: invalid type: map, expected a string at line 1 column 36

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>